name: Heavycoin
markdown: redcarpet
pygments: true
BMbroadcastAddr: BM-2cV6qRmeK677qYBetTMXmVmu6vGo3Pn4GG
BMKeccak: BM-NBuu8hBFdnqAeKs42Yg7nftB3QLfJ8ra
BMNomisugi: BM-NBAsCmCqUYR8eaXgs8zebDNPw5rUyM1z
HVCIPOAddr: 19VzBYvffPj4JcJM6ieNBXLEY9dJBQ2oXa
BTTANN: https://bitcointalk.org/index.php?topic=470391
BTTINFO: https://bitcointalk.org/index.php?topic=470391
twitterurl: https://twitter.com/heavycoinnews 
redditurl: xhttp://www.reddit.com/user/HeavyCoin-HVC
